// The Teacher Vault -- Spelling Challenge word bank.
// "Y3-4" and "Y5-6" words are the statutory National Curriculum in England spelling
// lists (English programmes of study, Key Stage 2, Appendix 1). "extra" words are
// additional practice words that are NOT part of the statutory lists -- they are
// clearly labelled as such throughout the app and must never be presented as
// statutory requirements.
window.TVSpelling = {
  words: [

    // ============================== YEAR 3/4 STATUTORY (100 words) ==============================
    { word:"accidentally", list:"Y3-4", pattern:"suffix -ally", clue:"by accident, not on purpose" },
    { word:"actually", list:"Y3-4", pattern:"suffix -ally", clue:"in actual fact; really" },
    { word:"address", list:"Y3-4", pattern:"double consonant", clue:"where someone lives; write it on a letter" },
    { word:"answer", list:"Y3-4", pattern:"silent letters", clue:"a reply to a question" },
    { word:"appear", list:"Y3-4", pattern:"double consonant", clue:"to come into view" },
    { word:"arrive", list:"Y3-4", pattern:"double consonant", clue:"to reach a place" },
    { word:"believe", list:"Y3-4", pattern:"ie or ei spelling", clue:"to think something is true" },
    { word:"bicycle", list:"Y3-4", pattern:"c sounding like s", clue:"a two-wheeled vehicle you pedal" },
    { word:"breath", list:"Y3-4", pattern:"silent letters", clue:"the air you take in (noun)" },
    { word:"breathe", list:"Y3-4", pattern:"silent letters", clue:"to take air in and out (verb)" },
    { word:"build", list:"Y3-4", pattern:"silent letters", clue:"to make something, like a house" },
    { word:"business", list:"Y3-4", pattern:"silent letters", clue:"a company or trade" },
    { word:"calendar", list:"Y3-4", pattern:"words ending -ar", clue:"shows the days and months of the year" },
    { word:"caught", list:"Y3-4", pattern:"-ough or -augh patterns", clue:"past tense of catch" },
    { word:"centre", list:"Y3-4", pattern:"c sounding like s", clue:"the middle of something" },
    { word:"century", list:"Y3-4", pattern:"c sounding like s", clue:"one hundred years" },
    { word:"certain", list:"Y3-4", pattern:"c sounding like s", clue:"sure about something" },
    { word:"circle", list:"Y3-4", pattern:"c sounding like s", clue:"a round shape" },
    { word:"complete", list:"Y3-4", pattern:"general", clue:"to finish something fully" },
    { word:"consider", list:"Y3-4", pattern:"general", clue:"to think carefully about" },
    { word:"continue", list:"Y3-4", pattern:"general", clue:"to keep going" },
    { word:"decide", list:"Y3-4", pattern:"general", clue:"to make a choice" },
    { word:"describe", list:"Y3-4", pattern:"general", clue:"to say what something is like" },
    { word:"different", list:"Y3-4", pattern:"general", clue:"not the same" },
    { word:"difficult", list:"Y3-4", pattern:"general", clue:"hard to do" },
    { word:"disappear", list:"Y3-4", pattern:"prefix dis-", clue:"to go out of sight" },
    { word:"early", list:"Y3-4", pattern:"general", clue:"before the usual time" },
    { word:"earth", list:"Y3-4", pattern:"general", clue:"the planet we live on" },
    { word:"eighth", list:"Y3-4", pattern:"silent letters", clue:"coming after seventh" },
    { word:"enough", list:"Y3-4", pattern:"silent gh", clue:"as much as is needed" },
    { word:"exercise", list:"Y3-4", pattern:"c sounding like s", clue:"physical activity to keep fit" },
    { word:"experience", list:"Y3-4", pattern:"c sounding like s", clue:"something that happens to you" },
    { word:"experiment", list:"Y3-4", pattern:"general", clue:"a scientific test" },
    { word:"extreme", list:"Y3-4", pattern:"general", clue:"very great in degree" },
    { word:"famous", list:"Y3-4", pattern:"suffix -ous", clue:"well known by many people" },
    { word:"favourite", list:"Y3-4", pattern:"general", clue:"the one you like best" },
    { word:"February", list:"Y3-4", pattern:"general", clue:"the second month of the year" },
    { word:"forwards", list:"Y3-4", pattern:"general", clue:"towards the front" },
    { word:"fruit", list:"Y3-4", pattern:"general", clue:"food that grows on trees or plants, like an apple" },
    { word:"grammar", list:"Y3-4", pattern:"words ending -ar", clue:"the rules of a language" },
    { word:"group", list:"Y3-4", pattern:"general", clue:"a number of people or things together" },
    { word:"guard", list:"Y3-4", pattern:"silent letters", clue:"to protect or watch over" },
    { word:"guide", list:"Y3-4", pattern:"silent letters", clue:"to show someone the way" },
    { word:"heard", list:"Y3-4", pattern:"general", clue:"past tense of hear" },
    { word:"heart", list:"Y3-4", pattern:"silent letters", clue:"the organ that pumps blood" },
    { word:"height", list:"Y3-4", pattern:"ie or ei spelling", clue:"how tall something is" },
    { word:"history", list:"Y3-4", pattern:"general", clue:"the study of the past" },
    { word:"imagine", list:"Y3-4", pattern:"general", clue:"to picture something in your mind" },
    { word:"increase", list:"Y3-4", pattern:"c sounding like s", clue:"to become bigger or more" },
    { word:"important", list:"Y3-4", pattern:"general", clue:"having great value or meaning" },
    { word:"interest", list:"Y3-4", pattern:"general", clue:"wanting to know more about something" },
    { word:"island", list:"Y3-4", pattern:"silent letters", clue:"land surrounded by water" },
    { word:"knowledge", list:"Y3-4", pattern:"silent letters", clue:"information and understanding" },
    { word:"learn", list:"Y3-4", pattern:"general", clue:"to gain knowledge or a skill" },
    { word:"length", list:"Y3-4", pattern:"general", clue:"how long something is" },
    { word:"library", list:"Y3-4", pattern:"words ending -ary -ery -ory", clue:"a place with lots of books" },
    { word:"material", list:"Y3-4", pattern:"general", clue:"fabric, or what something is made from" },
    { word:"medicine", list:"Y3-4", pattern:"c sounding like s", clue:"used to treat illness" },
    { word:"mention", list:"Y3-4", pattern:"general", clue:"to speak briefly about" },
    { word:"minute", list:"Y3-4", pattern:"general", clue:"sixty seconds" },
    { word:"natural", list:"Y3-4", pattern:"general", clue:"existing in nature, not made by people" },
    { word:"naughty", list:"Y3-4", pattern:"-ough or -augh patterns", clue:"badly behaved" },
    { word:"notice", list:"Y3-4", pattern:"c sounding like s", clue:"to see or become aware of" },
    { word:"occasionally", list:"Y3-4", pattern:"double consonant", clue:"sometimes, not often" },
    { word:"often", list:"Y3-4", pattern:"silent letters", clue:"many times" },
    { word:"opposite", list:"Y3-4", pattern:"general", clue:"completely different, the other way round" },
    { word:"ordinary", list:"Y3-4", pattern:"words ending -ary -ery -ory", clue:"normal, not special" },
    { word:"particular", list:"Y3-4", pattern:"general", clue:"specific; one in particular" },
    { word:"peculiar", list:"Y3-4", pattern:"general", clue:"strange or unusual" },
    { word:"perhaps", list:"Y3-4", pattern:"general", clue:"maybe" },
    { word:"popular", list:"Y3-4", pattern:"words ending -ar", clue:"liked by many people" },
    { word:"position", list:"Y3-4", pattern:"-tion or -sion endings", clue:"where something is placed" },
    { word:"possess", list:"Y3-4", pattern:"double consonant", clue:"to own something" },
    { word:"possible", list:"Y3-4", pattern:"double consonant", clue:"able to happen or be done" },
    { word:"potatoes", list:"Y3-4", pattern:"general", clue:"a vegetable that grows underground" },
    { word:"pressure", list:"Y3-4", pattern:"double consonant", clue:"a force pressing on something" },
    { word:"probably", list:"Y3-4", pattern:"general", clue:"likely to happen" },
    { word:"promise", list:"Y3-4", pattern:"c sounding like s", clue:"to say you will definitely do something" },
    { word:"purpose", list:"Y3-4", pattern:"c sounding like s", clue:"the reason for doing something" },
    { word:"quarter", list:"Y3-4", pattern:"general", clue:"one of four equal parts" },
    { word:"question", list:"Y3-4", pattern:"-tion or -sion endings", clue:"something you ask" },
    { word:"recent", list:"Y3-4", pattern:"c sounding like s", clue:"happened not long ago" },
    { word:"regular", list:"Y3-4", pattern:"words ending -ar", clue:"happening often, at even times" },
    { word:"reign", list:"Y3-4", pattern:"silent letters", clue:"the period a king or queen rules" },
    { word:"remember", list:"Y3-4", pattern:"general", clue:"to keep something in your memory" },
    { word:"sentence", list:"Y3-4", pattern:"c sounding like s", clue:"a group of words that make a complete thought" },
    { word:"separate", list:"Y3-4", pattern:"general", clue:"not joined together; to divide" },
    { word:"special", list:"Y3-4", pattern:"c sounding like s", clue:"not ordinary; important" },
    { word:"straight", list:"Y3-4", pattern:"silent gh", clue:"not bent or curved" },
    { word:"strange", list:"Y3-4", pattern:"general", clue:"unusual or surprising" },
    { word:"strength", list:"Y3-4", pattern:"general", clue:"physical power" },
    { word:"suppose", list:"Y3-4", pattern:"c sounding like s", clue:"to think something is likely true" },
    { word:"surprise", list:"Y3-4", pattern:"c sounding like s", clue:"an unexpected event" },
    { word:"therefore", list:"Y3-4", pattern:"general", clue:"for that reason" },
    { word:"although", list:"Y3-4", pattern:"silent gh", clue:"despite the fact that" },
    { word:"thought", list:"Y3-4", pattern:"-ough or -augh patterns", clue:"an idea, or past tense of think" },
    { word:"through", list:"Y3-4", pattern:"silent gh", clue:"from one side to the other" },
    { word:"various", list:"Y3-4", pattern:"suffix -ous", clue:"several different kinds" },
    { word:"weight", list:"Y3-4", pattern:"ie or ei spelling", clue:"how heavy something is" },
    { word:"woman", list:"Y3-4", pattern:"general", clue:"an adult female person" },

    // ============================== YEAR 5/6 STATUTORY (100 words) ==============================
    { word:"accommodate", list:"Y5-6", pattern:"double consonant", clue:"to provide space or lodging for" },
    { word:"accompany", list:"Y5-6", pattern:"general", clue:"to go along with someone" },
    { word:"according", list:"Y5-6", pattern:"general", clue:"as stated by; in agreement with" },
    { word:"achieve", list:"Y5-6", pattern:"ie or ei spelling", clue:"to succeed in doing something" },
    { word:"aggressive", list:"Y5-6", pattern:"double consonant", clue:"ready to attack or fight" },
    { word:"amateur", list:"Y5-6", pattern:"general", clue:"someone who does something for enjoyment, not pay" },
    { word:"ancient", list:"Y5-6", pattern:"general", clue:"very old, from long ago" },
    { word:"apparent", list:"Y5-6", pattern:"double consonant", clue:"clearly seen or understood" },
    { word:"appreciate", list:"Y5-6", pattern:"double consonant", clue:"to be grateful for something" },
    { word:"attached", list:"Y5-6", pattern:"double consonant", clue:"joined or fixed to something" },
    { word:"available", list:"Y5-6", pattern:"general", clue:"able to be used or obtained" },
    { word:"average", list:"Y5-6", pattern:"general", clue:"the usual or typical amount" },
    { word:"awkward", list:"Y5-6", pattern:"general", clue:"uncomfortable or clumsy" },
    { word:"bargain", list:"Y5-6", pattern:"silent letters", clue:"something bought cheaply" },
    { word:"bruise", list:"Y5-6", pattern:"general", clue:"a dark mark on skin after a knock" },
    { word:"category", list:"Y5-6", pattern:"words ending -ary -ery -ory", clue:"a group of similar things" },
    { word:"cemetery", list:"Y5-6", pattern:"words ending -ary -ery -ory", clue:"a place where people are buried" },
    { word:"committee", list:"Y5-6", pattern:"double consonant", clue:"a group chosen to organise something" },
    { word:"communicate", list:"Y5-6", pattern:"c sounding like s", clue:"to share information with others" },
    { word:"community", list:"Y5-6", pattern:"general", clue:"a group of people living in one area" },
    { word:"competition", list:"Y5-6", pattern:"-tion or -sion endings", clue:"a contest to find a winner" },
    { word:"conscience", list:"Y5-6", pattern:"c sounding like s", clue:"your inner sense of right and wrong" },
    { word:"conscious", list:"Y5-6", pattern:"suffix -ous", clue:"awake and aware" },
    { word:"controversy", list:"Y5-6", pattern:"general", clue:"a disagreement about something" },
    { word:"convenience", list:"Y5-6", pattern:"c sounding like s", clue:"something that makes life easier" },
    { word:"correspond", list:"Y5-6", pattern:"general", clue:"to match, or to write letters to someone" },
    { word:"criticise", list:"Y5-6", pattern:"general", clue:"to point out faults" },
    { word:"curiosity", list:"Y5-6", pattern:"general", clue:"a strong wish to know something" },
    { word:"definite", list:"Y5-6", pattern:"general", clue:"certain, without doubt" },
    { word:"desperate", list:"Y5-6", pattern:"general", clue:"feeling you have no other choice" },
    { word:"determined", list:"Y5-6", pattern:"general", clue:"having firmly decided to do something" },
    { word:"develop", list:"Y5-6", pattern:"general", clue:"to grow or become more advanced" },
    { word:"dictionary", list:"Y5-6", pattern:"words ending -ary -ery -ory", clue:"a book that explains word meanings" },
    { word:"disastrous", list:"Y5-6", pattern:"suffix -ous", clue:"extremely unsuccessful; terrible" },
    { word:"embarrass", list:"Y5-6", pattern:"double consonant", clue:"to make someone feel awkward" },
    { word:"environment", list:"Y5-6", pattern:"general", clue:"the natural world around us" },
    { word:"equipment", list:"Y5-6", pattern:"general", clue:"tools or items needed for a task" },
    { word:"especially", list:"Y5-6", pattern:"suffix -ally", clue:"more than usual; particularly" },
    { word:"exaggerate", list:"Y5-6", pattern:"double consonant", clue:"to make something seem bigger than it is" },
    { word:"excellent", list:"Y5-6", pattern:"double consonant", clue:"extremely good" },
    { word:"existence", list:"Y5-6", pattern:"c sounding like s", clue:"the state of being real" },
    { word:"explanation", list:"Y5-6", pattern:"-tion or -sion endings", clue:"a description that makes something clear" },
    { word:"familiar", list:"Y5-6", pattern:"words ending -ar", clue:"well known to you" },
    { word:"foreign", list:"Y5-6", pattern:"ie or ei spelling", clue:"from another country" },
    { word:"forty", list:"Y5-6", pattern:"general", clue:"the number 40" },
    { word:"frequently", list:"Y5-6", pattern:"general", clue:"often" },
    { word:"government", list:"Y5-6", pattern:"general", clue:"the group that runs a country" },
    { word:"guarantee", list:"Y5-6", pattern:"silent letters", clue:"a firm promise" },
    { word:"harass", list:"Y5-6", pattern:"double consonant", clue:"to bother someone repeatedly" },
    { word:"hindrance", list:"Y5-6", pattern:"general", clue:"something that gets in the way" },
    { word:"identity", list:"Y5-6", pattern:"general", clue:"who a person is" },
    { word:"immediately", list:"Y5-6", pattern:"double consonant", clue:"right away, at once" },
    { word:"individual", list:"Y5-6", pattern:"general", clue:"a single person" },
    { word:"interfere", list:"Y5-6", pattern:"general", clue:"to get involved where you're not wanted" },
    { word:"interrupt", list:"Y5-6", pattern:"double consonant", clue:"to break in while someone is speaking" },
    { word:"language", list:"Y5-6", pattern:"general", clue:"the words a country or people use to talk" },
    { word:"leisure", list:"Y5-6", pattern:"ie or ei spelling", clue:"free time for relaxing" },
    { word:"lightning", list:"Y5-6", pattern:"general", clue:"the flash of light in a storm" },
    { word:"marvellous", list:"Y5-6", pattern:"suffix -ous", clue:"wonderful; excellent" },
    { word:"mischievous", list:"Y5-6", pattern:"suffix -ous", clue:"naughty in a playful way" },
    { word:"muscle", list:"Y5-6", pattern:"c sounding like s", clue:"body tissue that helps you move" },
    { word:"necessary", list:"Y5-6", pattern:"words ending -ary -ery -ory", clue:"needed; essential" },
    { word:"neighbour", list:"Y5-6", pattern:"ie or ei spelling", clue:"someone who lives next door" },
    { word:"nuisance", list:"Y5-6", pattern:"c sounding like s", clue:"something annoying" },
    { word:"occupy", list:"Y5-6", pattern:"double consonant", clue:"to live in or fill a space" },
    { word:"occur", list:"Y5-6", pattern:"double consonant", clue:"to happen" },
    { word:"opportunity", list:"Y5-6", pattern:"double consonant", clue:"a good chance to do something" },
    { word:"parliament", list:"Y5-6", pattern:"silent letters", clue:"the group that makes a country's laws" },
    { word:"persuade", list:"Y5-6", pattern:"general", clue:"to convince someone to do something" },
    { word:"physical", list:"Y5-6", pattern:"general", clue:"relating to the body, not the mind" },
    { word:"prejudice", list:"Y5-6", pattern:"c sounding like s", clue:"an unfair opinion formed without good reason" },
    { word:"privilege", list:"Y5-6", pattern:"general", clue:"a special right or advantage" },
    { word:"profession", list:"Y5-6", pattern:"-tion or -sion endings", clue:"a job that needs special training" },
    { word:"programme", list:"Y5-6", pattern:"double consonant", clue:"a planned series of events, or a TV show" },
    { word:"pronunciation", list:"Y5-6", pattern:"general", clue:"the way a word is said aloud" },
    { word:"queue", list:"Y5-6", pattern:"general", clue:"a line of people waiting" },
    { word:"recognise", list:"Y5-6", pattern:"c sounding like s", clue:"to know something you've seen before" },
    { word:"recommend", list:"Y5-6", pattern:"double consonant", clue:"to suggest something is good" },
    { word:"relevant", list:"Y5-6", pattern:"general", clue:"connected to what is being discussed" },
    { word:"restaurant", list:"Y5-6", pattern:"general", clue:"a place where you buy and eat meals" },
    { word:"rhyme", list:"Y5-6", pattern:"silent letters", clue:"words that end with the same sound" },
    { word:"rhythm", list:"Y5-6", pattern:"silent letters", clue:"a regular repeated pattern of sound" },
    { word:"sacrifice", list:"Y5-6", pattern:"c sounding like s", clue:"to give something up for something else" },
    { word:"secretary", list:"Y5-6", pattern:"words ending -ary -ery -ory", clue:"someone who organises office work" },
    { word:"shoulder", list:"Y5-6", pattern:"general", clue:"the joint connecting your arm to your body" },
    { word:"signature", list:"Y5-6", pattern:"c sounding like s", clue:"your name written in your own handwriting" },
    { word:"sincerely", list:"Y5-6", pattern:"general", clue:"genuinely, honestly; used to end a letter" },
    { word:"soldier", list:"Y5-6", pattern:"general", clue:"a member of the army" },
    { word:"stomach", list:"Y5-6", pattern:"general", clue:"the organ where food is digested" },
    { word:"sufficient", list:"Y5-6", pattern:"c sounding like s", clue:"enough for what is needed" },
    { word:"suggest", list:"Y5-6", pattern:"general", clue:"to put forward an idea" },
    { word:"symbol", list:"Y5-6", pattern:"general", clue:"a sign that represents something else" },
    { word:"system", list:"Y5-6", pattern:"general", clue:"a set of parts working together" },
    { word:"temperature", list:"Y5-6", pattern:"general", clue:"how hot or cold something is" },
    { word:"thorough", list:"Y5-6", pattern:"silent gh", clue:"complete and careful, missing nothing" },
    { word:"twelfth", list:"Y5-6", pattern:"general", clue:"coming after eleventh" },
    { word:"variety", list:"Y5-6", pattern:"general", clue:"a range of different things" },
    { word:"vegetable", list:"Y5-6", pattern:"general", clue:"a plant food like a carrot or potato" },
    { word:"vehicle", list:"Y5-6", pattern:"silent letters", clue:"something used for transport, like a car" },
    { word:"yacht", list:"Y5-6", pattern:"silent letters", clue:"a boat used for racing or pleasure trips" },

    // ============================== EXTRA PRACTICE (not statutory) ==============================
    { word:"beautiful", list:"extra", pattern:"suffix -ful", clue:"very pretty or attractive" },
    { word:"definitely", list:"extra", pattern:"general", clue:"without any doubt" },
    { word:"tomorrow", list:"extra", pattern:"double consonant", clue:"the day after today" },
    { word:"beginning", list:"extra", pattern:"double consonant", clue:"the start of something" },
    { word:"until", list:"extra", pattern:"general", clue:"up to the time that" },
    { word:"friend", list:"extra", pattern:"ie or ei spelling", clue:"someone you like and trust" },
    { word:"because", list:"extra", pattern:"general", clue:"for the reason that" },
    { word:"again", list:"extra", pattern:"general", clue:"one more time" },
    { word:"always", list:"extra", pattern:"general", clue:"at all times, every time" },
    { word:"another", list:"extra", pattern:"general", clue:"one more, or a different one" },
    { word:"everybody", list:"extra", pattern:"general", clue:"every person" },
    { word:"everyone", list:"extra", pattern:"general", clue:"every person" },
    { word:"sudden", list:"extra", pattern:"general", clue:"happening quickly, without warning" },
    { word:"terrible", list:"extra", pattern:"general", clue:"very bad" },
    { word:"horrible", list:"extra", pattern:"general", clue:"very unpleasant" },
    { word:"visible", list:"extra", pattern:"general", clue:"able to be seen" },
    { word:"responsible", list:"extra", pattern:"general", clue:"having a duty to take care of something" },
    { word:"comfortable", list:"extra", pattern:"general", clue:"cosy and pleasant to use or wear" },
    { word:"reasonable", list:"extra", pattern:"general", clue:"fair and sensible" },
    { word:"valuable", list:"extra", pattern:"general", clue:"worth a lot" },
    { word:"disappoint", list:"extra", pattern:"prefix dis-", clue:"to fail to meet expectations" },
    { word:"embarrassed", list:"extra", pattern:"double consonant", clue:"feeling awkward or ashamed" },
    { word:"excitement", list:"extra", pattern:"general", clue:"a feeling of great enthusiasm" },
    { word:"imagination", list:"extra", pattern:"-tion or -sion endings", clue:"the ability to form pictures in your mind" },
    { word:"celebration", list:"extra", pattern:"-tion or -sion endings", clue:"an event to mark something special" },
    { word:"celebrate", list:"extra", pattern:"general", clue:"to mark a special occasion" },
    { word:"decision", list:"extra", pattern:"-tion or -sion endings", clue:"a choice you make" },
    { word:"division", list:"extra", pattern:"-tion or -sion endings", clue:"splitting something into parts; a maths operation" },
    { word:"invitation", list:"extra", pattern:"-tion or -sion endings", clue:"a request for someone to come to something" },
    { word:"information", list:"extra", pattern:"-tion or -sion endings", clue:"facts or details about something" },
    { word:"television", list:"extra", pattern:"-tion or -sion endings", clue:"a screen you watch programmes on" },
    { word:"umbrella", list:"extra", pattern:"double consonant", clue:"used to keep you dry in the rain" },
    { word:"elephant", list:"extra", pattern:"general", clue:"a very large grey animal with a trunk" },
    { word:"dinosaur", list:"extra", pattern:"general", clue:"an ancient reptile that no longer exists" },
    { word:"chocolate", list:"extra", pattern:"general", clue:"a sweet brown treat made from cacao" },
    { word:"holiday", list:"extra", pattern:"general", clue:"a trip or time off school or work" },
    { word:"weekend", list:"extra", pattern:"general", clue:"Saturday and Sunday" },
    { word:"birthday", list:"extra", pattern:"general", clue:"the day you were born, celebrated each year" }

  ]
};
