/* ==========================================================================
   The Teacher Vault -- KS1 Phonics Practice word bank.

   Levels are our own difficulty grouping (Starter / Building / Confident),
   NOT official government phonics phase labels -- the task spec is explicit
   that phase numbers must not be used unless verified, so we deliberately
   avoid them here.

   Every word is a real, common, decodable English word (UK spelling and
   pronunciation assumed). No invented words appear in this general-practice
   bank. Several graphemes genuinely represent more than one sound in
   English (e.g. "oo" in "moon" vs "book", "ow" in "snow" vs "cow") -- both
   are deliberately included so the tool never implies a grapheme always
   makes one fixed sound.

   `icon` is only set where a single emoji unambiguously represents the
   word on its own (the "Which Word?" mode is the only mode that needs a
   picture); words where no confident match exists simply have no icon.
   ========================================================================== */

window.TVPhonicsWords = [
  // ---------------- STARTER: simple CVC + common consonant digraph endings ----------------
  { word: "cat", grapheme: "c", level: "starter", icon: "🐱" },
  { word: "dog", grapheme: "d", level: "starter", icon: "🐶" },
  { word: "sun", grapheme: "s", level: "starter", icon: "☀️" },
  { word: "map", grapheme: "m", level: "starter" },
  { word: "pig", grapheme: "p", level: "starter", icon: "🐷" },
  { word: "hat", grapheme: "h", level: "starter", icon: "🎩" },
  { word: "cup", grapheme: "c", level: "starter", icon: "☕" },
  { word: "bed", grapheme: "b", level: "starter", icon: "🛏️" },
  { word: "leg", grapheme: "l", level: "starter", icon: "🦵" },
  { word: "sit", grapheme: "s", level: "starter" },
  { word: "run", grapheme: "r", level: "starter", icon: "🏃" },
  { word: "fox", grapheme: "f", level: "starter", icon: "🦊" },
  { word: "hen", grapheme: "h", level: "starter", icon: "🐔" },
  { word: "net", grapheme: "n", level: "starter", icon: "🥅" },
  { word: "web", grapheme: "w", level: "starter", icon: "🕸️" },
  { word: "box", grapheme: "b", level: "starter", icon: "📦" },
  { word: "bus", grapheme: "b", level: "starter", icon: "🚌" },
  { word: "mud", grapheme: "m", level: "starter" },
  { word: "tub", grapheme: "t", level: "starter", icon: "🛁" },
  { word: "kid", grapheme: "k", level: "starter", icon: "🧒" },
  { word: "jam", grapheme: "j", level: "starter", icon: "🍯" },
  { word: "log", grapheme: "l", level: "starter", icon: "🪵" },
  { word: "mop", grapheme: "m", level: "starter", icon: "🧹" },
  { word: "bag", grapheme: "b", level: "starter", icon: "👜" },
  { word: "pen", grapheme: "p", level: "starter", icon: "🖊️" },
  { word: "back", grapheme: "ck", level: "starter" },
  { word: "kick", grapheme: "ck", level: "starter" },
  { word: "sock", grapheme: "ck", level: "starter", icon: "🧦" },
  { word: "duck", grapheme: "ck", level: "starter", icon: "🦆" },
  { word: "neck", grapheme: "ck", level: "starter" },
  { word: "sack", grapheme: "ck", level: "starter" },
  { word: "lock", grapheme: "ck", level: "starter", icon: "🔒" },
  { word: "rock", grapheme: "ck", level: "starter", icon: "🪨" },
  { word: "pick", grapheme: "ck", level: "starter" },
  { word: "tick", grapheme: "ck", level: "starter" },
  { word: "bell", grapheme: "ll", level: "starter", icon: "🔔" },
  { word: "hill", grapheme: "ll", level: "starter", icon: "⛰️" },
  { word: "doll", grapheme: "ll", level: "starter", icon: "🪆" },
  { word: "fell", grapheme: "ll", level: "starter" },
  { word: "well", grapheme: "ll", level: "starter" },
  { word: "miss", grapheme: "ss", level: "starter" },
  { word: "kiss", grapheme: "ss", level: "starter" },
  { word: "boss", grapheme: "ss", level: "starter" },
  { word: "off", grapheme: "ff", level: "starter" },
  { word: "cliff", grapheme: "ff", level: "starter" },

  // ---------------- BUILDING: common digraphs ----------------
  { word: "ship", grapheme: "sh", level: "building", icon: "🚢" },
  { word: "shop", grapheme: "sh", level: "building", icon: "🏪" },
  { word: "shell", grapheme: "sh", level: "building", icon: "🐚" },
  { word: "fish", grapheme: "sh", level: "building", icon: "🐟" },
  { word: "wish", grapheme: "sh", level: "building" },
  { word: "dish", grapheme: "sh", level: "building", icon: "🍽️" },
  { word: "brush", grapheme: "sh", level: "building", icon: "🖌️" },
  { word: "crash", grapheme: "sh", level: "building", icon: "💥" },
  { word: "shut", grapheme: "sh", level: "building" },
  { word: "flash", grapheme: "sh", level: "building" },

  { word: "chip", grapheme: "ch", level: "building", icon: "🍟" },
  { word: "chat", grapheme: "ch", level: "building" },
  { word: "chin", grapheme: "ch", level: "building" },
  { word: "much", grapheme: "ch", level: "building" },
  { word: "such", grapheme: "ch", level: "building" },
  { word: "rich", grapheme: "ch", level: "building" },
  { word: "lunch", grapheme: "ch", level: "building", icon: "🍱" },
  { word: "chimp", grapheme: "ch", level: "building", icon: "🐵" },
  { word: "chest", grapheme: "ch", level: "building" },
  { word: "March", grapheme: "ch", level: "building" },

  { word: "this", grapheme: "th", level: "building" },
  { word: "that", grapheme: "th", level: "building" },
  { word: "then", grapheme: "th", level: "building" },
  { word: "moth", grapheme: "th", level: "building" },
  { word: "bath", grapheme: "th", level: "building", icon: "🛁" },
  { word: "path", grapheme: "th", level: "building" },
  { word: "thin", grapheme: "th", level: "building" },
  { word: "with", grapheme: "th", level: "building" },
  { word: "cloth", grapheme: "th", level: "building" },
  { word: "thick", grapheme: "th", level: "building" },

  { word: "king", grapheme: "ng", level: "building", icon: "👑" },
  { word: "ring", grapheme: "ng", level: "building", icon: "💍" },
  { word: "song", grapheme: "ng", level: "building", icon: "🎵" },
  { word: "long", grapheme: "ng", level: "building" },
  { word: "sing", grapheme: "ng", level: "building" },
  { word: "wing", grapheme: "ng", level: "building" },
  { word: "bang", grapheme: "ng", level: "building" },
  { word: "hang", grapheme: "ng", level: "building" },
  { word: "gang", grapheme: "ng", level: "building" },
  { word: "strong", grapheme: "ng", level: "building", icon: "💪" },

  { word: "rain", grapheme: "ai", level: "building", icon: "🌧️" },
  { word: "main", grapheme: "ai", level: "building" },
  { word: "pain", grapheme: "ai", level: "building" },
  { word: "snail", grapheme: "ai", level: "building", icon: "🐌" },
  { word: "chain", grapheme: "ai", level: "building", icon: "⛓️" },
  { word: "paint", grapheme: "ai", level: "building", icon: "🎨" },
  { word: "train", grapheme: "ai", level: "building", icon: "🚂" },
  { word: "wait", grapheme: "ai", level: "building" },
  { word: "aim", grapheme: "ai", level: "building" },
  { word: "sail", grapheme: "ai", level: "building", icon: "⛵" },

  { word: "tree", grapheme: "ee", level: "building", icon: "🌳" },
  { word: "feet", grapheme: "ee", level: "building", icon: "🦶" },
  { word: "green", grapheme: "ee", level: "building", icon: "🟩" },
  { word: "sleep", grapheme: "ee", level: "building", icon: "😴" },
  { word: "sheep", grapheme: "ee", level: "building", icon: "🐑" },
  { word: "seed", grapheme: "ee", level: "building", icon: "🌱" },
  { word: "queen", grapheme: "ee", level: "building", icon: "👸" },
  { word: "need", grapheme: "ee", level: "building" },
  { word: "keep", grapheme: "ee", level: "building" },
  { word: "week", grapheme: "ee", level: "building" },

  { word: "boat", grapheme: "oa", level: "building", icon: "⛵" },
  { word: "coat", grapheme: "oa", level: "building", icon: "🧥" },
  { word: "goat", grapheme: "oa", level: "building", icon: "🐐" },
  { word: "road", grapheme: "oa", level: "building", icon: "🛣️" },
  { word: "soap", grapheme: "oa", level: "building", icon: "🧼" },
  { word: "foam", grapheme: "oa", level: "building" },
  { word: "load", grapheme: "oa", level: "building" },
  { word: "coach", grapheme: "oa", level: "building", icon: "🚌" },
  { word: "roast", grapheme: "oa", level: "building" },
  { word: "toast", grapheme: "oa", level: "building", icon: "🍞" },

  { word: "moon", grapheme: "oo", level: "building", icon: "🌙" },
  { word: "spoon", grapheme: "oo", level: "building", icon: "🥄" },
  { word: "boot", grapheme: "oo", level: "building", icon: "👢" },
  { word: "zoom", grapheme: "oo", level: "building" },
  { word: "tooth", grapheme: "oo", level: "building", icon: "🦷" },
  { word: "book", grapheme: "oo", level: "building", icon: "📖" },
  { word: "look", grapheme: "oo", level: "building" },
  { word: "cook", grapheme: "oo", level: "building", icon: "🍳" },
  { word: "wood", grapheme: "oo", level: "building", icon: "🪵" },
  { word: "good", grapheme: "oo", level: "building" },

  // ---------------- CONFIDENT: trigraphs and further patterns ----------------
  { word: "night", grapheme: "igh", level: "confident", icon: "🌃" },
  { word: "light", grapheme: "igh", level: "confident", icon: "💡" },
  { word: "right", grapheme: "igh", level: "confident" },
  { word: "sight", grapheme: "igh", level: "confident" },
  { word: "high", grapheme: "igh", level: "confident" },
  { word: "fight", grapheme: "igh", level: "confident" },
  { word: "might", grapheme: "igh", level: "confident" },
  { word: "tight", grapheme: "igh", level: "confident" },
  { word: "bright", grapheme: "igh", level: "confident" },
  { word: "flight", grapheme: "igh", level: "confident", icon: "✈️" },

  { word: "car", grapheme: "ar", level: "confident", icon: "🚗" },
  { word: "star", grapheme: "ar", level: "confident", icon: "⭐" },
  { word: "farm", grapheme: "ar", level: "confident", icon: "🚜" },
  { word: "park", grapheme: "ar", level: "confident" },
  { word: "shark", grapheme: "ar", level: "confident", icon: "🦈" },
  { word: "arm", grapheme: "ar", level: "confident" },
  { word: "dark", grapheme: "ar", level: "confident" },
  { word: "scarf", grapheme: "ar", level: "confident", icon: "🧣" },
  { word: "sharp", grapheme: "ar", level: "confident" },
  { word: "garden", grapheme: "ar", level: "confident" },

  { word: "fork", grapheme: "or", level: "confident", icon: "🍴" },
  { word: "corn", grapheme: "or", level: "confident", icon: "🌽" },
  { word: "storm", grapheme: "or", level: "confident", icon: "⛈️" },
  { word: "sport", grapheme: "or", level: "confident" },
  { word: "short", grapheme: "or", level: "confident" },
  { word: "torch", grapheme: "or", level: "confident", icon: "🔦" },
  { word: "horse", grapheme: "or", level: "confident", icon: "🐴" },
  { word: "morning", grapheme: "or", level: "confident" },
  { word: "orbit", grapheme: "or", level: "confident" },
  { word: "acorn", grapheme: "or", level: "confident" },

  { word: "fur", grapheme: "ur", level: "confident" },
  { word: "hurt", grapheme: "ur", level: "confident" },
  { word: "curl", grapheme: "ur", level: "confident" },
  { word: "turn", grapheme: "ur", level: "confident" },
  { word: "burn", grapheme: "ur", level: "confident", icon: "🔥" },
  { word: "church", grapheme: "ur", level: "confident", icon: "⛪" },
  { word: "nurse", grapheme: "ur", level: "confident" },
  { word: "purple", grapheme: "ur", level: "confident", icon: "🟣" },
  { word: "surf", grapheme: "ur", level: "confident", icon: "🏄" },
  { word: "Thursday", grapheme: "ur", level: "confident" },

  { word: "snow", grapheme: "ow", level: "confident", icon: "❄️" },
  { word: "grow", grapheme: "ow", level: "confident" },
  { word: "show", grapheme: "ow", level: "confident" },
  { word: "slow", grapheme: "ow", level: "confident" },
  { word: "own", grapheme: "ow", level: "confident" },
  { word: "cow", grapheme: "ow", level: "confident", icon: "🐄" },
  { word: "how", grapheme: "ow", level: "confident" },
  { word: "now", grapheme: "ow", level: "confident" },
  { word: "brown", grapheme: "ow", level: "confident", icon: "🟤" },
  { word: "owl", grapheme: "ow", level: "confident", icon: "🦉" },

  { word: "coin", grapheme: "oi", level: "confident" },
  { word: "join", grapheme: "oi", level: "confident" },
  { word: "point", grapheme: "oi", level: "confident", icon: "👉" },
  { word: "voice", grapheme: "oi", level: "confident" },
  { word: "noise", grapheme: "oi", level: "confident" },
  { word: "soil", grapheme: "oi", level: "confident" },
  { word: "boil", grapheme: "oi", level: "confident" },
  { word: "oil", grapheme: "oi", level: "confident" },
  { word: "spoil", grapheme: "oi", level: "confident" },
  { word: "moist", grapheme: "oi", level: "confident" },

  { word: "hear", grapheme: "ear", level: "confident", icon: "👂" },
  { word: "near", grapheme: "ear", level: "confident" },
  { word: "year", grapheme: "ear", level: "confident" },
  { word: "gear", grapheme: "ear", level: "confident", icon: "⚙️" },
  { word: "fear", grapheme: "ear", level: "confident" },
  { word: "dear", grapheme: "ear", level: "confident" },
  { word: "clear", grapheme: "ear", level: "confident" },
  { word: "ear", grapheme: "ear", level: "confident", icon: "👂" },
  { word: "beard", grapheme: "ear", level: "confident" },
  { word: "spear", grapheme: "ear", level: "confident" },

  { word: "hair", grapheme: "air", level: "confident" },
  { word: "fair", grapheme: "air", level: "confident" },
  { word: "chair", grapheme: "air", level: "confident", icon: "🪑" },
  { word: "stairs", grapheme: "air", level: "confident" },
  { word: "pair", grapheme: "air", level: "confident" },
  { word: "air", grapheme: "air", level: "confident" },
  { word: "fairy", grapheme: "air", level: "confident", icon: "🧚" },
  { word: "repair", grapheme: "air", level: "confident" },
  { word: "dairy", grapheme: "air", level: "confident" },
  { word: "airport", grapheme: "air", level: "confident", icon: "🛫" }
];

/* ------------------------------------------------------------------
   Hand-checked "Build the Word" items -- explicit letter/grapheme
   chunks rather than an automatic splitter, so every segmentation is
   verifiably correct. Joining `chunks` always reproduces `word`
   exactly (verified by a standalone script before this file ships).
   ------------------------------------------------------------------ */
window.TVPhonicsBuildWords = [
  // starter
  { word: "cat", chunks: ["c", "a", "t"], level: "starter" },
  { word: "dog", chunks: ["d", "o", "g"], level: "starter" },
  { word: "sun", chunks: ["s", "u", "n"], level: "starter" },
  { word: "hat", chunks: ["h", "a", "t"], level: "starter" },
  { word: "pig", chunks: ["p", "i", "g"], level: "starter" },
  { word: "back", chunks: ["b", "a", "ck"], level: "starter" },
  { word: "sock", chunks: ["s", "o", "ck"], level: "starter" },
  { word: "bell", chunks: ["b", "e", "ll"], level: "starter" },
  { word: "hill", chunks: ["h", "i", "ll"], level: "starter" },
  { word: "miss", chunks: ["m", "i", "ss"], level: "starter" },
  // building
  { word: "ship", chunks: ["sh", "i", "p"], level: "building" },
  { word: "shop", chunks: ["sh", "o", "p"], level: "building" },
  { word: "fish", chunks: ["f", "i", "sh"], level: "building" },
  { word: "chip", chunks: ["ch", "i", "p"], level: "building" },
  { word: "chat", chunks: ["ch", "a", "t"], level: "building" },
  { word: "much", chunks: ["m", "u", "ch"], level: "building" },
  { word: "this", chunks: ["th", "i", "s"], level: "building" },
  { word: "moth", chunks: ["m", "o", "th"], level: "building" },
  { word: "bath", chunks: ["b", "a", "th"], level: "building" },
  { word: "king", chunks: ["k", "i", "ng"], level: "building" },
  { word: "song", chunks: ["s", "o", "ng"], level: "building" },
  { word: "wing", chunks: ["w", "i", "ng"], level: "building" },
  { word: "rain", chunks: ["r", "ai", "n"], level: "building" },
  { word: "tail", chunks: ["t", "ai", "l"], level: "building" },
  { word: "paint", chunks: ["p", "ai", "n", "t"], level: "building" },
  { word: "tree", chunks: ["tr", "ee"], level: "building" },
  { word: "feet", chunks: ["f", "ee", "t"], level: "building" },
  { word: "sleep", chunks: ["s", "l", "ee", "p"], level: "building" },
  { word: "boat", chunks: ["b", "oa", "t"], level: "building" },
  { word: "coat", chunks: ["c", "oa", "t"], level: "building" },
  { word: "road", chunks: ["r", "oa", "d"], level: "building" },
  { word: "moon", chunks: ["m", "oo", "n"], level: "building" },
  { word: "book", chunks: ["b", "oo", "k"], level: "building" },
  { word: "food", chunks: ["f", "oo", "d"], level: "building" },
  // confident
  { word: "night", chunks: ["n", "igh", "t"], level: "confident" },
  { word: "light", chunks: ["l", "igh", "t"], level: "confident" },
  { word: "high", chunks: ["h", "igh"], level: "confident" },
  { word: "car", chunks: ["c", "ar"], level: "confident" },
  { word: "star", chunks: ["st", "ar"], level: "confident" },
  { word: "farm", chunks: ["f", "ar", "m"], level: "confident" },
  { word: "for", chunks: ["f", "or"], level: "confident" },
  { word: "fork", chunks: ["f", "or", "k"], level: "confident" },
  { word: "corn", chunks: ["c", "or", "n"], level: "confident" },
  { word: "fur", chunks: ["f", "ur"], level: "confident" },
  { word: "turn", chunks: ["t", "ur", "n"], level: "confident" },
  { word: "burn", chunks: ["b", "ur", "n"], level: "confident" },
  { word: "snow", chunks: ["sn", "ow"], level: "confident" },
  { word: "grow", chunks: ["gr", "ow"], level: "confident" },
  { word: "cow", chunks: ["c", "ow"], level: "confident" },
  { word: "coin", chunks: ["c", "oi", "n"], level: "confident" },
  { word: "join", chunks: ["j", "oi", "n"], level: "confident" },
  { word: "point", chunks: ["p", "oi", "n", "t"], level: "confident" },
  { word: "hear", chunks: ["h", "ear"], level: "confident" },
  { word: "near", chunks: ["n", "ear"], level: "confident" },
  { word: "year", chunks: ["y", "ear"], level: "confident" },
  { word: "hair", chunks: ["h", "air"], level: "confident" },
  { word: "fair", chunks: ["f", "air"], level: "confident" },
  { word: "chair", chunks: ["ch", "air"], level: "confident" }
];
